server:
  port: 3344
  
spring:  application:    name: yaoxi-micro-config-3344
  cloud:    config:
      server:
        git:
          uri: https://github.com/Try118/yaoxi-micro-config.git
